package net.categoricaldata.category.functor.withLocallyFinitelyGeneratedSource
import net.categoricaldata.category._

trait withFinitelyGeneratedTarget extends functor.withSmallSource.withFinitelyGeneratedTarget with functor.withLocallyFinitelyGeneratedSource.withLocallyFinitelyGeneratedTarget
