package net.categoricaldata.category.functor.withFinitelyPresentedSource
import net.categoricaldata.category._

trait withFinitelyGeneratedTarget extends functor.withFinitelyGeneratedSource.withFinitelyGeneratedTarget with functor.withFinitelyPresentedSource.withLocallyFinitelyGeneratedTarget
