package net.categoricaldata.category.functor.withFinitelyPresentedSource
import net.categoricaldata.category._

  trait withSmallTarget extends functor.withFinitelyGeneratedSource.withSmallTarget with Functor.withFinitelyPresentedSource
  trait withLocallyFinitelyGeneratedTarget extends functor.withFinitelyGeneratedSource.withLocallyFinitelyGeneratedTarget with functor.withFinitelyPresentedSource.withSmallTarget
  trait withFinitelyGeneratedTarget extends functor.withFinitelyGeneratedSource.withFinitelyGeneratedTarget with functor.withFinitelyPresentedSource.withLocallyFinitelyGeneratedTarget
  trait withFinitelyPresentedTarget extends functor.withFinitelyGeneratedSource.withFinitelyPresentedTarget with functor.withFinitelyPresentedSource.withFinitelyGeneratedTarget
