package net.categoricaldata.category.functor.withSmallSource
import net.categoricaldata.category._

trait withFinitelyGeneratedTarget extends functor.withSmallSource.withLocallyFinitelyGeneratedTarget with Functor.withFinitelyGeneratedTarget