package net.categoricaldata.category.functor.withSmallSource
import net.categoricaldata.category._

trait withFinitelyPresentedTarget extends functor.withSmallSource.withFinitelyGeneratedTarget with Functor.withFinitelyPresentedTarget
