package net.categoricaldata.category.functor.withSmallSource
import net.categoricaldata.category._

trait withLocallyFinitelyGeneratedTarget extends functor.withSmallSource.withSmallTarget with Functor.withLocallyFinitelyGeneratedTarget